# Generated by Django 4.2.7 on 2023-11-23 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syrius", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="syrius",
            old_name="image",
            new_name="photo",
        ),
    ]
