# Generated by Django 4.2.7 on 2023-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syrius", "0002_rename_image_syrius_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="syrius",
            old_name="photo",
            new_name="image",
        ),
    ]
