# Generated by Django 4.2.7 on 2023-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syrius", "0003_rename_photo_syrius_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syrius",
            name="image",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
