# Generated by Django 4.2.7 on 2023-11-24 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syrius", "0004_alter_syrius_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="syrius",
            old_name="content",
            new_name="description",
        ),
    ]
